name: Update Artalk Binary

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "gopcn"
          git config --global user.email "121377609+gopcn@users.noreply.github.com"

      - name: Get latest release
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ArtalkJS/Artalk
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and Extract Artalk
        run: curl -sL "https://github.com/ArtalkJS/Artalk/releases/download/${{ steps.get-latest-release.outputs.release }}/artalk_${{ steps.get-latest-release.outputs.release }}_linux_amd64.tar.gz" | tar -zxv --strip-components=1

      - name: Commit Changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.AUTH_PAT }}
          commit-message: "${{ steps.get-latest-release.outputs.release }}"
          files: artalk artalk.yml
          rebase: 'true'
          name: gopcn
          email: 121377609+gopcn@users.noreply.github.com