name: Update Memos and Create Release

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get latest release
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: usememos/memos
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Release
        run: |
          git clone https://github.com/usememos/memos.git build
          cd build/web
          yarn && yarn build
          cd ..
          cp -r -f web/dist ./server
          go build -o memos ./main.go
          rm -rf ../memos && cp -r -f ./memos ../
          cd ..

      - name: Commit Changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ steps.get-latest-release.outputs.release }}"
          files: memos
          rebase: 'true'
          name: GitHub Action
          email: action@github.com

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: memos
          tag_name: ${{ steps.get-latest-release.outputs.release }}
          title: Release ${{ steps.get-latest-release.outputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}